### ISSUE TITLE
About tuning VoodooPS2 in https://github.com/icedman/OS-X-Voodoo-PS2-Controller

### ISSUE THREAD

**Issue by syscl** [icedman/XPS13-9350-hackintosh#1]
Hi @icedman ,

I'm sorry to post issue in a wrong place, but I can't post issue [here](https://github.com/icedman/OS-X-Voodoo-PS2-Controller). That's the reason why I post VoodooPS2 issue here.

I tried your version of VoodooPS2, which is much better than RehabMan's one. Stable and more functional. I read your code, but I haven't had experience in changing VoodooPS2's code, thus I want to ask for your help.

For example, if I want to set 3finger swipe left as "Show the previous page", 3finger swipe right as 
"Show the next page", how to map it to key shortcut to "Command + [" and "Command + ]"?

And, how to implement 3finger pinch/tap then remap it to look up dictionary?

Above two functions I've implemented in AppleSmartTouchPad.kext, and it work nicely in El Captain. But the recent update of AppleSmartTouchPad takes too long, I don't want to wait. I really want to do something to make our XPS 13 better. So could you please give me some hints to refine it?

Thanks for your great change!
syscl

**Comment by icedman** [comment]
I pushed by latest today so you can test. See readme for gestures that you can use. 

The default is that 3 finger swipe is just the same as 4 finger swipe. 
But you can change them Info.plist, or through ioio (NOT TESTED!). Or you can change the defaults in the source code. The key shortcuts are found in VoodooPS2Keyboard.cpp:

// Setup default swipe actions
parseAction("3b d, 37 d, 7e d, 7e u, 37 u, 3b u", _actionSwipeUp, countof(_actionSwipeUp));
.. etc

Note that "TrackpadThreeFingerDrag" must be disabled if you want to use 3 fingers gestures. 
And also note that I increased the swiping threshold, tweaked to my taste. You can only currently change this in the source code.

**Comment by syscl** [comment]
@icedman Thank you!! Together we make our XPS 13 better than ever!

Do you try the latest deploy.sh?

I will report here later, thank you for your modification, I am very appreciate!

Have a good day,
syscl

**Comment by icedman** [comment]
You're welcome. Thank you for your work also.

I still use my own deploy script (which was based on your previous project). Whenever possible, I only apply patches and fixes that I understand. I don't use thunderbolt or external displays so my setup is near perfect for my own use.

I do keep up to date with your changes and copy your patches whenever applicable.

**Comment by syscl** [comment]
@icedman A few questions, Does the latest VoodooPS2 you modified have the 3f swipe up and down, 4f up and down function?

How to customized them? For example if I want to map 3f swipe left to "Command + [", how to generate the mapping code?

Thanks in advance,
syscl

**Comment by icedman** [comment]
I do not think I changed the 3f swipe from rehabman's code. But it can be customized in the plist.

for example: "3b d, 37 d, 37 u, 3b u" 
'd' means down, 'u' means up. the preceeding number is the keycode.

the keycodes can be generated by turning on "LogScanCodes" in the plist or through ioio and spying the console output when you press any key.
 
$> ioio -S ApplePS2Keyboard LogScanCodes 1 

try something like:

$> ioio -S ApplePS2Keyboard ActionSwipeUp "3b d, 37d ..."

Something else:

The new gestures "ActionSwipe4FingersUp" must be added in the plist. Doing ioio now without an entry in the plist will add a number instead of a string.

**Comment by syscl** [comment]
@icedman Thank you, I will try it now!

Is there a way to implement 2finger tap and 3finger tap?

Thank you,
syscl

**Comment by syscl** [comment]
Hi @icedman 

I try to build the latest VoodooPS2 from your git, and get this error(change scheme to build all kext):
![snip20170122_1](https://cloud.githubusercontent.com/assets/11594858/22192742/216bc3bc-e0fc-11e6-8bee-79f3913b3c34.png)

syscl

**Comment by icedman** [comment]
I might have failed to push a few other files. Please pull again and let me know.
I think 3f tap would be easy to implement. I will try on the weekend. 
2f tap was already implemented show the context menu.

**Comment by syscl** [comment]
@icedman Build successfully.

But 4finger swipe has no response. I even try to set 4f swipe in keyboard..

Thank you,
syscl

**Comment by icedman** [comment]
Please check if keycodes are generated. 
Check if keycodes are generated in the keyboard setting > shortcuts.
Also, for finger swipes, I set the threshold higher. Try making longer swipes on the trackpad.

**Comment by syscl** [comment]
@icedman Nice, it seems I finally manage to change the code and make VoodooPS2 work.

What I change is 3 finger swipe left mapping to show the previous page, which is:
```
"37 d, 21 d, 21 u, 37 u"
```

3finger swipe right maps to show next page:
```
37 d, 1e d, 1e u, 37 u
```

syscl

**Comment by syscl** [comment]
I found that the function of 3finger left/right swipe will lose response somehow. Is that because of you improve the swiping threshold? This one: ```DragExitDelayTime```?

I will try and report here.

Edited: I tried to lower down ```DragExitDelayTime``` and disable three finger drag, but still no go. What's worse, 3finger swipe left/right almost unusable unless I assign them to "Move a left space" and "Move right space" 

Here's the log, but only very few of them will "show previous page" and "show next page":
![snip20170123_1](https://cloud.githubusercontent.com/assets/11594858/22196443/d48ee0a8-e112-11e6-8c56-4228f3477ccc.png)

And I don't know why Move left a space become "Command + left arrow" and Move right a space becomes "Command + right arrow"
![snip20170123_2](https://cloud.githubusercontent.com/assets/11594858/22196476/fc1695a8-e112-11e6-9177-c4d7be5e4512.png)

It should be "Command + [" and "Command + ]". 

Thank you,
syscl

**Comment by icedman** [comment]
DragExitDelayTime is for dragging.

search swipeThresh variable in the code. choose (1,2,3). 1 for lowest/sensitive;
also make sure to set TrackpadThreeFingerDrag is set to false.

tluck's implementation of the three-finger drag does not work well with my 3 gestures detection. 

sometimes the gestures are not correctly detected. probably because from my implementation which only determines starting and ending positions of fingers.

**Comment by syscl** [comment]
@icedman Weird, after changing ```ActionSwipeLeft``` and ```ActionSwipeLeft``` in both  ```VoodooPS2Keyboard-Info.plis``` and ```VoodooPS2Keyboard-Breakless-Info``` , 3finger swipe left/right behaves normally. 

So does that means we cannot simply change ```VoodooPS2Keyboard.kext``` and Info.plist in ```VoodooPS2Keyboard.kext```? We must change ```VoodooPS2Keyboard.cpp```, ```VoodooPS2Keyboard-Info.plis``` and ```VoodooPS2Keyboard-Breakless-Info``` before compiling?

Now 3finger swipe behaves pretty well(like AppleSmartTouchPad). Could you give me some feedback(3finger swipe left/right) about the following version of VoodooPS2? 
[VoodooPS2Controller.kext.zip](https://github.com/icedman/XPS13-9350-hackintosh/files/723056/VoodooPS2Controller.kext.zip)

Thank you!
syscl

**Comment by syscl** [comment]
BTW, I can confirm 4finger swipe work as expect. 

Edited: Aha, I figure out that the swipeThresh value = 1 is best for 3/4 finger swipe. Butter smooth. Even better than AppleSmartTouchPad! Nice!
[VoodooPS2Controller.kext.zip](https://github.com/icedman/XPS13-9350-hackintosh/files/723095/VoodooPS2Controller.kext.zip)


BTW, could you show some lights on which is 2finger tap remapping? Thanks for your patience and make VoodooPS2 great again!

Thank you,
syscl

**Comment by icedman** [comment]
It looks like 2finger tap and 3finger tap are currently made to simulate right click and 3rd button click of a mouse by enabling TrackpadRightClick. It should be easy to customize and add our own function.

I can do more tests on the weekend.

**Comment by syscl** [comment]
@icedman Thank you, is there a way to detect 3 finger tap? Since we have 3finger swipe...

syscl

**Comment by icedman** [comment]
3/4 finger tap can be added. I'll try to add it later tonight.

**Comment by syscl** [comment]
Thank you!

syscl

**Comment by icedman** [comment]
$ioio -s ApplePS2Keyboard Action3FingersTap :"37 d, 31 d, 31 u, 37 u"
$ioio -s ApplePS2Keyboard Action4FingersTap :""

there is also a Action2FingersTap.
the two fingers detection also now better

make sure to disable trackpadrightclick if you want to use 2 fingers tap.
i also lowered the thresholds in the source code

**Comment by syscl** [comment]
Hi @icedman 

Nice work. 3f/2f tap detection is pretty sensitive, top! But the problem is when I map 3finger to look up function(control + command + d = 3b d, 37 d, 2 d, 2 u, 37 u, 3b u ) it do not work as expect. Seems VoodooPS2 do some extra keys after 3finger tap.

Thank you,
syscl

**Comment by syscl** [comment]
@icedman But when I map 4finger to look up function, look up works pretty well! 

Then I set both 3finger and 4finger as look up function, still 4finger work as expect. But 3 finger do not. Seems 3finger tap is too sensitive to cause some issue?

syscl

**Comment by icedman** [comment]
i made some more fine tuning. please test.
2 finger tap and 3 finger tap can now only be used with TrackpadRightClick set to false.

There still seems to be a problem with two finger tap with Voodoops2 still sending some keys.

**Comment by syscl** [comment]
@icedman If TrackpadRightClick set to false, then 2finger tap won't perform as right click anymore?

syscl

**Comment by icedman** [comment]
yes. also 3 finger click won't simulate middle mouse button.

right click and finger taps can't be used together.

if you want the right click and middle button clicks
set Action2FingersTap :""

4 finger taps has no problem. (i think)

**Comment by syscl** [comment]
@icedman I will report here soon.

syscl

**Comment by syscl** [comment]
Hi @icedman how to set TrackpadRightClick to false? I just found there's two place contains TrackpadRightClick, and there's no boolean value..

Thank you,
syscl

**Comment by syscl** [comment]
@icedman is weird, after using the latest commit, there's no more 3finger tap log in console and yes, no 3finger tap gesture. But previous version can detect 3finger tap.. 

syscl

**Comment by icedman** [comment]
please try to update (pull).
make sure to set voodoo settings.. $ ./voodoops2ioio.sh . found in the root folder. you can edit your settings here

**Comment by syscl** [comment]
OK, I remove your git repo and git clone, that's my way to use latest commit everytime. Because that can ensure all your code is clean.

I change 3 place:  code, VoodooPS2Keyboard-Breakless-Info and VoodooPS2Keyboard-Breakless-Info to set settings. 

Still 3finger tap cannot be detected. 
4finger tap is nice, but I need to improve threshold since it's too sensitive.

Anyway, thank you for bringing these features together, it's really nice.
syscl

**Comment by icedman** [comment]
please try 

$ ioio -s ApplePS2SynapticsTouchPad TrackpadRightClick 0

**Comment by syscl** [comment]
@icedman after applying 
```
ioio -s ApplePS2SynapticsTouchPad TrackpadRightClick 0
```
3finger and 4finger tap work as expect! But we lost two finger tap. Anyway to prevent using ioio and make both 2finger as right click 3finger tap work?

Thank you!
syscl

**Comment by syscl** [comment]
@icedman I know what's wrong. In the code, I will pull request to you later.

Now I will tune the delay time of 3/4finger tap, because is too sensitive.

Again, thank you for you bring this together!
syscl

**Comment by icedman** [comment]
Anyway to prevent using ioio and make both 2finger as right click 3finger tap work?

search "send tap event" in the synaptics source file.
search the code for "multitouchcount == 3 && threeFignerTapDetected" , move the code block outside the  "if (rtap)", and put it beside fourFingersTap

**Comment by syscl** [comment]
Just move threeFingerTapDetected outside rtap, that's not enough. Also need to remove 
```
if (threeFingerTapDetected) {
                buttons |= !swapdoubletriple ? 0x4 : 0x02;
}
```

But, as you suggest, I will try to see if this remove is necessary.
syscl

**Comment by icedman** [comment]
ok. we should have a different setting like TrackpadMiddleClick.

there is also another "buttons |= !swapdoubletriple ? 0x4 : 0x02;"  somewhere above from rehabman's implementation

note: 2 finger tap is interefereing with scrolling. I'm testing now a fix

**Comment by icedman** [comment]
I now added TrackpadMiddleClick
and fixed 2 finger tap bug.

My code has fourfingersdetected all over the the place. I still need to apply threeFingersDetected similarly to improve 3 fingers. 

If the kext is usable and stable for you, I will leave it as is for now.

**Comment by syscl** [comment]
Thank you for your hard work @icedman I will continue to report if there's some other issues.

One of the minor issue is zoom in and zoom out, it always causes casually zoom in/out, same issue on AppleSmartTouchPad, that's the reason why I disable this feature on AppleSmartTouchPad.

Another problem is that 3finger swipe always not functional, I mean I always need to swipe two or three times to trigger swipe left/right. AppleSmartTouchPad work almost perfectly in this case.

3/4 finger tap is too sensitive, is there a way to improve the detect time. For example, if my 3 finger tap on the trackpad last about 1s~more, then VoodooPS2 treat it as 3finger tap, then call 3finger shortcut. 

Wish this suggestion could improve your project! Thank you!
syscl

**Comment by icedman** [comment]
to disable ActionZoomIn & ActionZoomOut .. set only to "" in plist or ioio

for sensitivity: experiment with editing maxtaptime in plist
or search  "detect multitouch tap"  and experiment with the times

**Comment by icedman** [comment]
currently the 3 finger swipe can only be done once for every second.
to experiment with different settings. search "case 1:"  and edit elapsed times
you can change NS_DISPATCH_WAIT (current 1 second) to other values

let me know your ideal settings.

**Comment by syscl** [comment]
Hi @icedman 

How about the latest deploy.sh with VoodooPS2(in my GitHub)?

I tried VoodooPS2 these days, seems very stable(But I do not update to your latest VoodooPS2 source code). 

syscl

**Comment by icedman** [comment]
I haven't tried your latest updates yet. 
I might try in the coming days, especially when my sound ALC256 sometimes gets lost after sleep. (I have to let the laptop sleep again to regain sound)

**Comment by syscl** [comment]
OK. I barely sleep XPS 13 because there will be data corruption. I don't know if data corruption issue is related to NVMe or Dell's firmware problem.

My version of AppleHDA and CodecCommander may solve your issue.

syscl

**Comment by icedman** [comment]
I always sleep, too lazy :) to shutdown.
I never had any corruption, but I only have the sata drive. and i disabled hibernation.

**Comment by syscl** [comment]
@icedman You do not have NVMe? Only AHCI device? So from the recent reinstall macOS, how long your data does not corrupt? 1 month? 2 months? or even longer?

I enjoy sleep function and M3800 sleeps pretty well. I barely shutdown M3800. That's the reason why I want to figure out what's wrong on XPS 13.

syscl

**Comment by icedman** [comment]
i don't have nvme, my xps13 is on the lower end specs.
