### ISSUE TITLE
VoodooPS2 on 10.8.5

### ISSUE THREAD

**Issue by y023rus** [icedman/XPS13-9350-hackintosh#2]
Dear icedman, would you be so kind to build your driver modification for 10.8.5? On 10.11.5 it's working really good but on 10.8.5 not working at all.

**Comment by icedman** [comment]
Please try this one 
https://github.com/icedman/XPS13-9350-hackintosh/blob/master/kexts/VoodooPS2Controller.kext.zip

**Comment by y023rus** [comment]
no, it doesn't work too. logs https://www.dropbox.com/s/edynmir0ygcqjb9/1.txt?dl=0

**Comment by icedman** [comment]
Please try again: https://github.com/icedman/XPS13-9350-hackintosh/blob/master/kexts
I now set the deployment target to macOS 10.8 from 10.6; But my base SDK is still for 10.12,
I did not have the chance to checked this on a hackintosh.
Also please try building yourself, if you have xcode installed.

**Comment by y023rus** [comment]
No, the same. I'll download xcode and try to build, thanks for attempts to help.

**Comment by icedman** [comment]
@y023rus were you able to build the kext for your os?
you could also ask help from syscl, his voodoops2 version was forked from this branch

**Comment by y023rus** [comment]
Kext were built with Xcode 5.1.1 installed but didn't work double tap and I couldn't do with it nothing (built in terminal with "make", in Xcode I couldn't build working driver). I tried syscl kext but it not works on 10.8.5 too, on 10.11.5 it works a bit worse then yours for my opinion.
